name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write        # allow commits
  actions: read          # allow API calls
  issues: read           # sometimes needed for stats
  pull-requests: read    # sometimes needed for stats

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Saravanakumar2602
          BRANCH_NAME: main
          AUTO_PUSH: true
